### ISSUE TITLE
Impossible de voir les rapprochements pour Grenoble

### ISSUE THREAD

**Issue by jazzzz** [osm-fr/osm-vs-fantoir#41]
Il y a une erreur dans la requête https://cadastre.openstreetmap.fr/fantoir/requete_fantoir.py?insee=38185.
Il se trouve qu'il y a très peu de voies de Grenoble dans BANO (63), je ne sais pas si c'est la même cause, mais c'est gênant pour diagnostiquer.

```
<!--: spam
Content-Type: text/html

<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
</table> </table> </table> </table> </table> </font> </font> </font><body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>&lt;class 'psycopg2.InternalError'&gt;</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 2.7.3: /usr/bin/python<br>Wed Apr 11 18:16:06 2018</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///data/project/cadastre.openstreetmap.fr/fantoir/requete_fantoir.py">/data/project/cadastre.openstreetmap.fr/fantoir/requete_fantoir.py</a> in <strong><module></strong>()</td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;82</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;83</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a&nbsp;=&nbsp;json.JSONEncoder().encode(data)<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;84</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(a)<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;85</small>&nbsp;if&nbsp;__name__&nbsp;==&nbsp;'__main__':<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;86</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main()<br>
</tt></td></tr>
<tr><td><small><font color="#909090"><strong>main</strong>&nbsp;= &lt;function main&gt;</font></small></td></tr></table>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///data/project/cadastre.openstreetmap.fr/fantoir/requete_fantoir.py">/data/project/cadastre.openstreetmap.fr/fantoir/requete_fantoir.py</a> in <strong>main</strong>()</td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;79</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;date_cache_highway_relation&nbsp;=&nbsp;get_fin_etape_dept(pgc,'cache_dept_highway_relation_insee',dept)[0]<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;80</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;81</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data&nbsp;=&nbsp;[[nom_commune,date_import_cadastre,date_fin_cumul[0],date_fin_cumul[1],date_cache_hsnr,date_cache_highway,date_cache_highway_relation,lon_commune,lat_commune,labels_statuts_fantoir,a_voisins],get_data_from_pg(pgc,'voies_adresses_non_rapprochees_insee',insee_com),get_data_from_pg(pgc,'voies_adresses_rapprochees_insee',insee_com),get_data_from_pg(pgc,'voies_seules_non_rapprochees_insee',insee_com),get_data_from_pg(pgc,'voies_seules_rapprochees_insee',insee_com),get_data_from_pg(pgc,'places_non_rapprochees_insee',insee_com),get_data_from_pg(pgc,'places_rapprochees_insee',insee_com)]<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;82</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;83</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a&nbsp;=&nbsp;json.JSONEncoder().encode(data)<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090">data <em>undefined</em>, <strong>nom_commune</strong>&nbsp;= 'Grenoble', <strong>date_import_cadastre</strong>&nbsp;= [('recupCadastre', 'CADASTRE', '30-12-2015 22:07:44')], <strong>date_fin_cumul</strong>&nbsp;= [('loadCumul', 'CADASTRE', None), ('loadCumul', 'OSM', '10-04-2018 21:56:52')], <strong>date_cache_hsnr</strong>&nbsp;= (1523389968.0, 'cache_dept_hsnr_insee', '10-04-2018 21:53:42'), <strong>date_cache_highway</strong>&nbsp;= (1523395761.0, 'cache_dept_highway_insee', '10-04-2018 23:30:44'), <strong>date_cache_highway_relation</strong>&nbsp;= (1523395858.0, 'cache_dept_highway_relation_insee', '10-04-2018 23:31:13'), <strong>lon_commune</strong>&nbsp;= 5.72108176979414, <strong>lat_commune</strong>&nbsp;= 45.1822777824233, <strong>labels_statuts_fantoir</strong>&nbsp;= [(0, 0, 'Ok'), (1, 1, "Erreur d'orthographe"), (2, 2, "Divergence d'orthographe"), (3, 3, 'Nom diff<font color="#c040c0">\xc3\xa9</font>rent'), (4, 4, 'Type de voie diff<font color="#c040c0">\xc3\xa9</font>rent'), (5, 5, 'Voie doublon et type de voie diff<font color="#c040c0">\xc3\xa9</font>rent'), (6, 6, 'Voie doublon avec orthographe diff<font color="#c040c0">\xc3\xa9</font>rente'), (7, 8, 'R<font color="#c040c0">\xc3\xa9</font>p<font color="#c040c0">\xc3\xa9</font>tition du type de voie'), (8, 9, 'Nom introuvable sur le terrain'), (9, 10, 'Ancien nom supprim<font color="#c040c0">\xc3\xa9</font> sur le terrain'), (10, 99, 'Erreurs combin<font color="#c040c0">\xc3\xa9</font>es'), (11, 15, 'Adresses hors p<font color="#c040c0">\xc3\xa9</font>rim<font color="#c040c0">\xc3\xa8</font>tre'), (12, 11, 'Voie d<font color="#c040c0">\xc3\xa9</font>truite'), (13, 12, 'Voie incorpor<font color="#c040c0">\xc3\xa9</font>e <font color="#c040c0">\xc3\xa0</font> une autre'), (14, 13, 'Voie inexistante'), (15, 7, 'Voie doublon (m<font color="#c040c0">\xc3\xaa</font>me type et m<font color="#c040c0">\xc3\xaa</font>me nom)'), (16, 11, 'Nom tronqu<font color="#c040c0">\xc3\xa9</font>'), (17, 16, 'Erreur de commune')], <strong>a_voisins</strong>&nbsp;= [[2, '38516', 'La Tronche'], [4, '38421', "Saint-Martin-d'H<font color="#c040c0">\xc3\xa8</font>res"], [5, '38158', 'Eybens'], [7, '38151', '<font color="#c040c0">\xc3\x89</font>chirolles'], [8, '38486', 'Seyssins'], [9, '38485', 'Seyssinet-Pariset'], [10, '38169', 'Fontaine'], [11, '38382', 'Saint-<font color="#c040c0">\xc3\x89</font>gr<font color="#c040c0">\xc3\xa8</font>ve'], [12, '38423', 'Saint-Martin-le-Vinoux']], <em>global</em> <strong>get_data_from_pg</strong>&nbsp;= &lt;function get_data_from_pg&gt;, <strong>pgc</strong>&nbsp;= &lt;connection object at 0x2410940; dsn: 'dbname='c...host='localhost' password=xxxxxxxxxx', closed: 0&gt;, <strong>insee_com</strong>&nbsp;= '38185'</font></small></td></tr></table>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///data/project/cadastre.openstreetmap.fr/fantoir/requete_fantoir.py">/data/project/cadastre.openstreetmap.fr/fantoir/requete_fantoir.py</a> in <strong>get_data_from_pg</strong>(pgc=&lt;connection object at 0x2410940; dsn: 'dbname='c...host='localhost' password=xxxxxxxxxx', closed: 0&gt;, data_type='voies_adresses_rapprochees_insee', insee_com='38185')</td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;21</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fq.close()<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;22</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cur&nbsp;=&nbsp;pgc.cursor()<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;23</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cur.execute(str_query)<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;24</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;res&nbsp;=&nbsp;cur.fetchall()<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;25</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;res<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090"><strong>cur</strong>&nbsp;= &lt;cursor object at 0x7fc577539ed8; closed: 0&gt;, cur.<strong>execute</strong>&nbsp;= &lt;built-in method execute of psycopg2._psycopg.cursor object&gt;, <strong>str_query</strong>&nbsp;= "SELECT<font color="#c040c0">\t</font>f.code_insee||f.id_voie||f.cle_rivoli fan...<font color="#c040c0">\t</font>AND<font color="#c040c0">\n\t\t</font>COALESCE(j.voie_osm,'') != ''<font color="#c040c0">\n</font>ORDER BY 3;<font color="#c040c0">\n</font>"</font></small></td></tr></table><p><strong>&lt;class 'psycopg2.InternalError'&gt;</strong>: Argument to X() must be a point

<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
('Argument to X() must be a point<font color="#c040c0">\n</font>',)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>cursor&nbsp;=
&lt;cursor object at 0x7fc577539ed8; closed: 0&gt;
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>message&nbsp;=
'Argument to X() must be a point<font color="#c040c0">\n</font>'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>pgcode&nbsp;=
'XX000'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>pgerror&nbsp;=
'ERROR:  Argument to X() must be a point<font color="#c040c0">\n</font>'


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "/data/project/cadastre.openstreetmap.fr/fantoir/requete_fantoir.py", line 86, in &lt;module&gt;
    main()
  File "/data/project/cadastre.openstreetmap.fr/fantoir/requete_fantoir.py", line 81, in main
    data = [[nom_commune,date_import_cadastre,date_fin_cumul[0],date_fin_cumul[1],date_cache_hsnr,date_cache_highway,date_cache_highway_relation,lon_commune,lat_commune,labels_statuts_fantoir,a_voisins],get_data_from_pg(pgc,'voies_adresses_non_rapprochees_insee',insee_com),get_data_from_pg(pgc,'voies_adresses_rapprochees_insee',insee_com),get_data_from_pg(pgc,'voies_seules_non_rapprochees_insee',insee_com),get_data_from_pg(pgc,'voies_seules_rapprochees_insee',insee_com),get_data_from_pg(pgc,'places_non_rapprochees_insee',insee_com),get_data_from_pg(pgc,'places_rapprochees_insee',insee_com)]
  File "/data/project/cadastre.openstreetmap.fr/fantoir/requete_fantoir.py", line 23, in get_data_from_pg
    cur.execute(str_query)
InternalError: Argument to X() must be a point


-->
```

**Comment by cquest** [comment]
Un problème lié aux données opendata de Grenoble (MULTIPOINT à la place de POINT)... en principe corrigé.
Cette erreur empêchait aussi la génération des fichiers csv sur le département 38.
